export const zhCN = {
  brand: {
    name: "JoyStorm AR",
    subtitle: "表情驱动的实时互动体验",
  },
  events: {
    waiting: "等待识别人脸",
    ready: "请尽情的绽放你的笑容吧",
    noFace: "没有检测到人脸，请移动到画面中央",
    smile: "检测到微笑，星字雨与涟漪已出现",
    laugh: "检测到张嘴大笑，烟花已绽放",
    requestingCamera: "正在请求摄像头权限",
    loadingModel: "正在加载人脸识别模型",
    calibratingStill: "正在校准中性表情，请保持自然",
    calibrating: (progress: number) => `正在校准中性表情 · ${progress}%`,
    modelPaused: "人脸模型暂时停顿，已暂停特效并等待恢复",
    cameraUnavailable: "摄像头暂时不可用",
    qaActive: "模拟体验已开启，请使用右侧测试按钮",
  },
  errors: {
    unsupportedCamera: "浏览器不支持。请使用最新版 Chrome 或 Safari。",
    missingVideo: "摄像头画面加载失败，请刷新页面后重试。",
    permissionDenied: "用户拒绝权限。请在浏览器设置中允许摄像头访问，然后重新尝试。",
    noCamera: "当前设备没有摄像头。请连接摄像头后重新尝试。",
    modelLoadFailed: "模型加载失败。请检查网络后重新尝试。",
    startupFailed: "摄像头或人脸识别模型启动失败，请稍后重试。",
  },
  engineStates: {
    faceLocked: "已识别人脸",
    searching: "正在寻找人脸",
    simulation: "模拟体验中",
    starting: "正在启动",
    offline: "尚未开启",
  },
  topbar: {
    showDiagnostics: "查看识别详情",
    hideDiagnostics: "收起识别详情",
  },
  stage: {
    label: "实时摄像头互动区",
    cameraLabel: "镜像显示的前置摄像头画面",
  },
  diagnostics: {
    label: "实时识别详情",
    signal: "实时信号",
    smile: "微笑强度",
    jaw: "张嘴幅度",
    particles: "粒子数量",
    rainParticles: "雨与符号",
    fireworkParticles: "烟花粒子",
    ripples: "涟漪数量",
    inference: "识别频率",
    collider: "头部碰撞区",
    tracked: "跟踪中",
    waiting: "等待中",
    state: "当前状态",
    smileThreshold: "微笑阈值",
    laughThreshold: "大笑阈值",
    cooldown: "恢复等待",
    rawSmile: "原始 Smile",
    smoothedSmile: "平滑 Smile",
    smileSides: "Smile 左 / 右",
    jawOpen: "jawOpen 原始 / 平滑",
    cheekSquint: "cheekSquint",
    laughComposite: "Laugh 笑意综合值",
    laughIntensity: "Laugh Intensity",
    candidateState: "Candidate State",
    stableState: "Stable State",
    candidateDuration: "Candidate 持续",
    smileThresholds: "Smile 进入 / 退出",
    laughSmileThresholds: "Laugh Smile 进入 / 退出",
    laughJawThresholds: "Laugh Jaw 进入 / 退出",
    rainEmission: "Rain Emission",
    rainIntensity: "Rain Intensity",
    faceTracking: "Face Tracking",
    faceTracked: "TRACKED",
    faceLost: "LOST",
    debugMode: "Firework Debug",
    debugHint: "点击画面可发射单朵测试烟花",
    collisionFunction: "碰撞功能",
    showCollider: "显示头部碰撞体",
    showEvidence: "显示碰撞证据",
    currentBurstCollisions: "本次烟花碰撞",
    sessionCollisions: "会话累计碰撞",
    lastCollision: "最近一次碰撞",
    colliderTracking: "碰撞体跟踪",
    collisionStatus: "Collision",
    on: "ON",
    off: "OFF",
    never: "尚未发生",
  },
  permission: {
    eyebrow: "实时表情互动",
    title: "你的笑容能带来温柔的细雨与灿烂的烟花",
    description: "微笑会唤来带着星星与字母的涟漪雨；张嘴大笑会让烟花从头顶绽放。所有识别都在当前设备完成。",
    mappingLabel: "表情与效果对应关系",
    smile: "微笑",
    rain: "星字雨与涟漪",
    laugh: "张嘴大笑",
    fireworks: "烟花",
    head: "头部轮廓",
    collision: "粒子碰撞",
    starting: "正在开启摄像头…",
    start: "开启摄像头体验",
    simulation: "先用模拟体验",
    privacy: "视频画面和面部数据只在当前设备中处理，不会上传或保存。",
  },
  signal: {
    section: "当前表情",
    laugh: "张嘴大笑",
    smile: "微笑",
    neutral: "中性",
    laughEffect: "烟花与头部碰撞已触发",
    smileEffect: "星字雨、涟漪与漂散正在生成",
    neutralEffect: "互动效果等待触发",
  },
  qa: {
    section: "效果测试",
    description: "以下按钮只模拟状态与特效，不代表真人表情识别结果。",
    neutral: "中性状态",
    smile: "微笑状态",
    laugh: "大笑状态",
  },
  performance: {
    section: "运行性能",
    budget: "粒子性能档位",
    auto: "自动 · 最多 400 个",
    high: "高质量 · 最多 460 个",
    lite: "流畅优先 · 最多 280 个",
    localRendering: "本地画布渲染",
    localDetection: "本地人脸识别",
    adaptiveResolution: "自适应清晰度与预算",
  },
  actions: {
    end: "结束本次体验",
  },
  footer: {
    local: "本地人脸识别",
    stable: "平滑与迟滞判定",
    physics: "椭圆碰撞与粒子物理",
  },
} as const;
